version: '3'
services:
  adu-nasib-api:
    image: postgres:14
    container_name: uts-sig-db
    restart: unless-stopped
    tty: true
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - uts-sig-network

volumes:
  uts-sig-db:

networks:
  uts-sig-network:
